AnnualCycle:
  _target_: metrics.module.SeasonalCycles
  variables:
    - {"name": "ta", "pressure_level": 85000}
    - {"name": "tas", "pressure_level": null}
    - {"name": "zg", "pressure_level": 50000}
  mean_groups:
    - "time.year"
    - "time.month"
  baseline_mean_groups:
    - "time.month"
  detrend: True
  linear_trend: False
  compute_anomalies: True
  baseline_period: ["1981-01-01", "2010-12-31"]
  plotter_kwargs:
    output_path: "timeseries/anomalies/an"
    figsize: [12, 8]  
    linewidth: 1.0

    