BiasMaps:
  _target_: metrics.module.XYBiasMaps
  xdim: "lon"
  ydim: "lat"
  temporal_selection: ["annual"]
  variables: 
    - {name: "tas", pressure_level: null} 
    - {name: "tos", pressure_level: null}
  plotter_kwargs:
    output_path: "seasonal_means"
