Histogram: 
  _target_: metrics.module.Histogram
  time: 
    #- ["1978-10-01", "1978-10-03"]
    #- ["1978-10-07", "1978-10-07"]
    #- ["1979-01-01", "1979-01-01"]
    #- ["1979-01-01", "1979-12-31"]
    - ["1979-01-01", "2014-12-31"]
  frequency: "daily"
  variables: 
    - ["hus", 70000]
    - ["hus", 85000]
    - ["zg", 50000]
    - ["uas", null]
    - ["vas", null]
    - ["ua", 85000]
    - ["va", 85000]
    - ["ta", 85000]
  plotter_kwargs:
    output_path: "histogram"
    linewidth: 1.0