NorthernAnnularMode:
  _target_: metrics.module.NorthernAnnularMode
  var: "psl"
  time: ["December", "January", "February"]
  method: "EOF"
  frequency: "monthly"
  latitude_bands: [20, 90]
  longitude_bands: Null
  per_member: True
  weight_by_latitude: True
  plotter_kwargs:
    output_path: "NAM"
    dpi: 300
    figsize: [6.7, 3.]