NorthernAnnularMode:
  _target_: metrics.module.NorthernAnnularMode
  var: "zg"
  time: ["November", "December", "January", "February"]
  method: "EOF"
  frequency: "monthly"
  latitude_bands: [20, 90]
  longitude_bands: Null
  plotter_kwargs:
    output_path: "NAM"