SeasonalMeans:
  _target_: metrics.module.XYMaps
  xdim: "lon"
  ydim: "lat"
  compute_rmse: false
  stack_models_in_rows: true
  temporal_selection: ["annual"]
  variables: 
    - {name: "ua", pressure_level: 20000}
    - {name: "va", pressure_level: 20000}
    - {name: "ua", pressure_level: 25000}
    - {name: "va", pressure_level: 25000}
    - {name: "ua", pressure_level: 30000}
    - {name: "va", pressure_level: 30000}
    - {name: "tas", pressure_level: null}
    - {name: "ta", pressure_level: 85000}
    #- {name: "uas", pressure_level: null}
    #- {name: "vas", pressure_level: null}
    #- {name: "ua", pressure_level: 85000}
    #- {name: "va", pressure_level: 85000}
    #- {name: "psl", pressure_level: null}
    #- {name: "zg", pressure_level: 50000}
    - {name: "hus", pressure_level: 85000}
    - {name: "hus", pressure_level: 70000}

  plotter_kwargs:
    output_path: "SeasonalMeans"
