spectrum:
  _target_: metrics.module.RadialSpectrum
  frequency: "daily"
  time_instances: 
    - ["2014-01-01", "2014-12-31"]
    #- ["1979-01-02", "1979-01-02"]
    
  variables: 
    - ["ua", 85000]
    - ["va", 85000]
    - ["hus", 70000]
    - ["zg", 50000]
    #- ["psl", null]
    #- ["hus", 85000]
    #- ["uas", null]
    #- ["vas", null]
    #- ["ta", 85000]  
  plotter_kwargs:
    output_path: "SphericalSpectra"
    linewidth: 1.0
    figsize: [6.7, 6]
    dpi: 300