# Specify which configs to use.
defaults:  
  - _self_
  - climdata: data  
  - eval: metrics

generic:
  restrict_to_time_range: ["1979-01-01", "2014-12-31"]

output_path: "./evalstore/results/ClimatologyWUnforced/Paper/1979-2014"
latitude: 181


  