# Specify which configs to use.
defaults:
  - data: data  
  - metrics: metrics
  - _self_

target_metrics:
  #- regression 
  #- annual_cycle
  #- anomaly_kde
  - lat_lon_avg
  #- pl_lat
  #- soi 
  #- spectrum

output_path: "./evalstore/results/paper/default_vs_sst_increases"
latitude: 181

