model_name: "AW-M-1-aimip-stats-forcings_surface"  # the name of the model under modelstore/
start_timestamp: "1980-01-01T12:00"
end_timestamp: "2019-12-31T12:00"
replace_nans_from_state: False

aimip:
  # Options: "modules.deterministic.DeterministicAAIMIPRollout", "modules.generative.GenerativeAAIMIPRollout"
  _target_: "modules.deterministic.DeterministicAAIMIPRollout" 
  aimip_name: "AW-M-1-aimip-stats-forcings_surface"
  member: 0
  grid_type: "gn" # Options: "gn", "ga", "gr"
  init_method: 1 # Options: 1, 2, 3, ...
  physics: 1 # Options: 1, 2, ...
  forcings: 1 # Options: 1, 2, ...
  sst_scenario: ''
  continue_rollout: False
  storage_type: "daily" # Options: "monthly", "daily"
  storage_path: evalstore/${aimip.aimip_name}/${start_timestamp}/${aimip.storage_type}
  store_initial_condition: True
  

  
