model_name: "AW-M-0-aimip-stats-forcings_surface-interpolgt"  # the name of the model under modelstore/
start_timestamp: "1980-01-01T12:00"
end_timestamp: "2039-12-31T12:00"
avg_with_modules: ["AW-M-0-aimip-stats-forcings_surface-interpolgt"] 

aimip:
  # Options: "modules.deterministic.DeterministicAAIMIPRollout", "modules.generative.GenerativeAAIMIPRollout"
  _target_: "modules.deterministic.DeterministicAAIMIPRollout" 
  aimip_name: "AW-M-0-aimip-stats-forcings_surface-interpolgt"
  member: "avg"
  grid_type: "gn" # Options: "gn", "ga", "gr"
  init_method: 1 # Options: 1, 2, 3, ...
  physics: 1 # Options: 1, 2, ...
  forcings: 1 # Options: 1, 2, ...
  sst_scenario: '0' # either '0', '2' or '4' indicating the sst scenario
  continue_rollout: True
  storage_type: "daily" # Options: "monthly", "daily"
  storage_path: evalstore/${aimip.aimip_name}/${start_timestamp}/sst_${aimip.sst_scenario}/${aimip.storage_type}
  store_initial_condition: True
  ablate_forcings: False
  

  
