defaults:
  - _self_
  - metrics/bias_maps.yaml
  - metrics/hist.yaml
  #- metrics/lat_time.yaml
  #- metrics/webster_yang.yaml
  #- metrics/seasonal_means.yaml
  #- metrics/annual_cycle.yaml
  #- metrics/nam.yaml
  #- metrics/nao.yaml
  #- metrics/soi.yaml