anomaly_kde:
  _target_: metrics.module.AnomalyKDE
  variables: 
    - ["temperature", 850]
  use_lat_weighting: "weatherbench"
  latitude: 181
  figsize: [12, 6]
  dpi: 150
  linewidth: 2
  base_period: [1993, 2010]