lat_lon_avg:
  _target_: metrics.module.XYPlot
  x: "longitude"
  y: "latitude"
  time: ["annual"]
  variables: 
    #- ["sea_surface_temperature", Null]
    #- ["sea_ice_cover", Null]
    - ["2m_temperature", Null]
    #- ["10m_u_component_of_wind", Null]
    #- ["temperature", 850]
    #- ["specific_humidity", 850]
  latitude: 181
  plot_type: "variable"
  diverging_cmap: "bwr"
  sequential_cmap: "PuBu"
  fontdict:
    axes.titlesize: 20
    axes.labelsize: 20
    xtick.labelsize: 13
    ytick.labelsize: 13
    legend.fontsize: 18
