MPI-M-ESM1-HR:
  path_to_monthly_data: 
    - "data/mpi-esm-1x1/amip/r1i1p1f1/Amon"
    - "data/mpi-esm-1x1/amip/r2i1p1f1/Amon"
    - "data/mpi-esm-1x1/amip/r3i1p1f1/Amon"
  path_to_daily_data: 
    - "data/mpi-esm-1x1/amip/r1i1p1f1/day"
    - "data/mpi-esm-1x1/amip/r2i1p1f1/day"
    - "data/mpi-esm-1x1/amip/r3i1p1f1/day"
  model_label: "MPI-ESM"
  color: [0.5, 0.5, 0.5] 
  period: ["1979-01-01", "2014-12-31"]
  is_reference: False
  