ArchesWeather-Ensemble":
  path_to_daily_data: 
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r1i1p1f1/day"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r2i1p1f1/day"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r3i1p1f1/day"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r4i1p1f1/day"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r5i1p1f1/day"
  path_to_monthly_data: 
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r1i1p1f1/Amon"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r2i1p1f1/Amon"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r3i1p1f1/Amon"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r4i1p1f1/Amon"
    - "rollouts/cmorised_aimip/ArchesWeather/full/0k/r5i1p1f1/Amon"
  model_label: "AWMx4"
  color: "#0072B2"  # some light blue color
  period: null #["1979-01-01", "2024-12-31"]
  is_reference: False