"AWGen-Unforced-Ensemble":
  path_to_daily_data:
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r1i1p1f1/4_cmorisation/day"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r2i1p1f1/4_cmorisation/day"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r3i1p1f1/4_cmorisation/day"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r4i1p1f1/4_cmorisation/day"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r5i1p1f1/4_cmorisation/day"
  path_to_monthly_data: 
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r1i1p1f1/4_cmorisation/Amon"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r2i1p1f1/4_cmorisation/Amon"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r3i1p1f1/4_cmorisation/Amon"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r4i1p1f1/4_cmorisation/Amon"
    - "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/ArchesWeatherGenU/full/0k/r5i1p1f1/4_cmorisation/Amon"
  model_label: "AWGen (U)"
  color: "#CC79A7"  # some purple color
  period: Null #["1979-01-01", "2024-12-31"]
  is_reference: False