"AWGen-Ensemble-2k":
  path_to_daily_data: 
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member1/day"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member2/day"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member3/day"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member4/day"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member5/day"
  path_to_monthly_data: 
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member1/Amon"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member2/Amon"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member3/Amon"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member4/Amon"
    - "/work/bk1450/a270220/cmorised_awm/forced_sst_2K/member5/Amon"
  model_label: "AWGen Ensemble (SST=2K)"
  color: [0.8, 0.0, 0.4]  # some blue color
  period: ["1979-01-01", "2024-12-31"]
  is_reference: False