AWM0_aimip_default_unforced:
  path_to_daily_data: Null
  path_to_monthly_data: "/home/b/b383170/repositories/geoarches_evaluation/evaluation/rollouts/cmorised_aimip/AWM0-aimip_default-unforced/0k/1978-10-01/mem1/4_cmorisation/Amon"
  model_label: "AWM-aimip (Member=1) SST=0k"
  color: [0.3, 0.3, 0.3]  
  period: ["1979-01-01", "2024-12-31"]